"""
Prototype A: Event-triggered playback and synchronization.

Workflow:
1. Play the match video through VLC.
2. Read events.csv generated by analyze_events.py.
3. Use VLC's actual playback position as the synchronization clock.
4. Send one serial command when each event time is reached:
       EVENT,SHOT
       EVENT,FOUL
       EVENT,PENALTY
       EVENT,GOAL
5. Record ESP32 serial output together with the current video time.
6. Send STOP whenever playback pauses, ends, fails, or the program exits.

Expected ESP32 commands:
    PING
    EVENT,SHOT
    EVENT,FOUL
    EVENT,PENALTY
    EVENT,GOAL
    STOP

Suggested ESP32 sensor output:
    DATA,esp_ms,bpm,ir,ax,ay,az,gx,gy,gz,active_event,led,vib,ptc

The logger also keeps the complete raw serial line, so small future changes to
the Arduino DATA format will not break data collection.
"""

from __future__ import annotations

import argparse
import bisect
import csv
import datetime as dt
import os
import queue
import sys
import threading
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import serial


VALID_EVENTS = {"SHOT", "FOUL", "PENALTY", "GOAL"}


@dataclass(frozen=True)
class MatchEvent:
    time_s: float
    event: str
    confidence: float
    text: str
    source_row: int


@dataclass
class SerialRecord:
    host_time: str
    monotonic_time: float
    line: str


def load_events(
    csv_path: Path,
    minimum_confidence: float,
    trigger_offset_s: float,
) -> list[MatchEvent]:
    events: list[MatchEvent] = []

    with csv_path.open("r", encoding="utf-8-sig", newline="") as file:
        reader = csv.DictReader(file)

        if not reader.fieldnames:
            raise RuntimeError("events.csv 没有表头。")

        required = {"time_s", "event", "confidence"}
        missing = required.difference(reader.fieldnames)

        if missing:
            raise RuntimeError(
                "events.csv 缺少字段：" + ", ".join(sorted(missing))
            )

        for row_number, row in enumerate(reader, start=2):
            try:
                event_time = float(row["time_s"])
                confidence = float(row["confidence"])
            except (TypeError, ValueError) as error:
                raise RuntimeError(
                    f"events.csv 第 {row_number} 行数值无效。"
                ) from error

            event_name = str(row["event"]).strip().upper()

            if event_name not in VALID_EVENTS:
                print(
                    f"跳过第 {row_number} 行未知事件：{event_name}",
                    file=sys.stderr,
                )
                continue

            if confidence < minimum_confidence:
                continue

            adjusted_time = max(0.0, event_time + trigger_offset_s)

            events.append(
                MatchEvent(
                    time_s=adjusted_time,
                    event=event_name,
                    confidence=max(0.0, min(1.0, confidence)),
                    text=str(row.get("text", "")).strip(),
                    source_row=row_number,
                )
            )

    events.sort(key=lambda item: item.time_s)

    if not events:
        raise RuntimeError(
            "没有满足条件的事件。请检查 events.csv 或降低 "
            "--min-confidence。"
        )

    return events


def configure_vlc_directory(vlc_dir: Path | None) -> None:
    """
    Make libvlc discoverable before importing python-vlc.
    """
    if os.name != "nt":
        return

    candidates: list[Path] = []

    if vlc_dir is not None:
        candidates.append(vlc_dir)

    candidates.extend(
        [
            Path(r"C:\Program Files\VideoLAN\VLC"),
            Path(r"C:\Program Files (x86)\VideoLAN\VLC"),
        ]
    )

    for candidate in candidates:
        if not (candidate / "libvlc.dll").exists():
            continue

        os.environ["PATH"] = (
            str(candidate)
            + os.pathsep
            + os.environ.get("PATH", "")
        )

        if hasattr(os, "add_dll_directory"):
            os.add_dll_directory(str(candidate))

        return


def import_vlc(vlc_dir: Path | None) -> Any:
    configure_vlc_directory(vlc_dir)

    try:
        import vlc
    except (ImportError, OSError) as error:
        raise RuntimeError(
            "无法加载 VLC。请安装 64 位 VLC 和 python-vlc，"
            "并确保它们与 Python 位数一致。"
        ) from error

    return vlc


def send_line(serial_port: serial.Serial, message: str) -> None:
    serial_port.write((message.rstrip() + "\n").encode("utf-8"))
    serial_port.flush()


def wait_for_ping(
    serial_port: serial.Serial,
    startup_wait_s: float = 3.0,
) -> bool:
    """
    Opening an ESP32 serial port often resets the board.
    Wait for startup messages, then verify the command protocol.
    """
    print("等待 ESP32 启动...")
    deadline = time.monotonic() + startup_wait_s

    while time.monotonic() < deadline:
        raw = serial_port.readline()

        if raw:
            line = raw.decode("utf-8", errors="replace").strip()

            if line:
                print("[ESP32]", line)

    send_line(serial_port, "PING")
    deadline = time.monotonic() + 2.0

    while time.monotonic() < deadline:
        raw = serial_port.readline()

        if not raw:
            continue

        line = raw.decode("utf-8", errors="replace").strip()

        if line:
            print("[ESP32]", line)

        if line == "ACK,PONG":
            return True

    return False


def serial_reader(
    serial_port: serial.Serial,
    output_queue: queue.Queue[SerialRecord],
    stop_event: threading.Event,
) -> None:
    while not stop_event.is_set():
        try:
            raw = serial_port.readline()
        except serial.SerialException:
            stop_event.set()
            break

        if not raw:
            continue

        line = raw.decode("utf-8", errors="replace").strip()

        if not line:
            continue

        output_queue.put(
            SerialRecord(
                host_time=dt.datetime.now().isoformat(
                    timespec="milliseconds"
                ),
                monotonic_time=time.monotonic(),
                line=line,
            )
        )


def create_log_files(
    output_dir: Path,
) -> tuple[Any, Any, Any, Any, Path, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    stamp = dt.datetime.now().strftime("%Y%m%d_%H%M%S")

    sensor_path = output_dir / f"sensor_data_{stamp}.csv"
    event_log_path = output_dir / f"event_commands_{stamp}.csv"

    sensor_file = sensor_path.open(
        "w",
        newline="",
        encoding="utf-8-sig",
        buffering=1,
    )
    event_log_file = event_log_path.open(
        "w",
        newline="",
        encoding="utf-8-sig",
        buffering=1,
    )

    sensor_writer = csv.writer(sensor_file)
    event_writer = csv.writer(event_log_file)

    sensor_writer.writerow(
        [
            "host_time",
            "video_time_s",
            "raw_serial_line",
            "esp_ms",
            "bpm",
            "ir",
            "ax",
            "ay",
            "az",
            "gx",
            "gy",
            "gz",
            "active_event",
            "led_pwm",
            "vib_pwm",
            "ptc_pwm",
        ]
    )

    event_writer.writerow(
        [
            "host_time",
            "video_time_s",
            "scheduled_time_s",
            "event",
            "confidence",
            "command",
            "commentary_text",
        ]
    )

    return (
        sensor_file,
        event_log_file,
        sensor_writer,
        event_writer,
        sensor_path,
        event_log_path,
    )


def parse_sensor_fields(line: str) -> list[str]:
    """
    Parse the suggested Prototype A DATA format.

    Expected:
    DATA,esp_ms,bpm,ir,ax,ay,az,gx,gy,gz,active_event,led,vib,ptc

    If the Arduino format changes, raw_serial_line is still preserved.
    """
    parts = line.split(",")

    if len(parts) == 14 and parts[0] == "DATA":
        return parts[1:]

    return [""] * 13


def drain_serial_queue(
    serial_queue: queue.Queue[SerialRecord],
    sensor_writer: Any,
    player: Any,
) -> None:
    while True:
        try:
            record = serial_queue.get_nowait()
        except queue.Empty:
            break

        video_ms = player.get_time()
        video_time_s = (
            max(0.0, video_ms / 1000.0)
            if video_ms >= 0
            else 0.0
        )

        if record.line.startswith("DATA,"):
            fields = parse_sensor_fields(record.line)
            sensor_writer.writerow(
                [
                    record.host_time,
                    f"{video_time_s:.3f}",
                    record.line,
                    *fields,
                ]
            )

        elif record.line.startswith(("READY", "ACK", "ERROR", "EVENT")):
            print("[ESP32]", record.line)


def wait_until_playing(
    player: Any,
    vlc: Any,
    timeout_s: float = 10.0,
) -> None:
    deadline = time.monotonic() + timeout_s

    while time.monotonic() < deadline:
        state = player.get_state()

        if state == vlc.State.Playing:
            return

        if state in (vlc.State.Error, vlc.State.Ended):
            raise RuntimeError(
                f"VLC 无法播放视频，当前状态：{state}"
            )

        time.sleep(0.05)

    raise RuntimeError("VLC 启动超时。")


def get_console_command() -> str | None:
    """
    Non-blocking Windows keyboard controls.

    Space: pause/resume
    A: rewind 10 s
    D: forward 10 s
    J: rewind 30 s
    L: forward 30 s
    Q: quit
    """
    if os.name != "nt":
        return None

    try:
        import msvcrt
    except ImportError:
        return None

    if not msvcrt.kbhit():
        return None

    key = msvcrt.getwch()

    if key == " ":
        return "toggle_pause"

    key = key.lower()

    mapping = {
        "a": "rewind_10",
        "d": "forward_10",
        "j": "rewind_30",
        "l": "forward_30",
        "q": "quit",
    }

    return mapping.get(key)


def seek_player(
    player: Any,
    offset_s: float,
) -> float:
    current_ms = player.get_time()

    if current_ms < 0:
        current_ms = 0

    length_ms = player.get_length()
    target_ms = current_ms + round(offset_s * 1000)

    if length_ms > 0:
        target_ms = min(target_ms, max(0, length_ms - 100))

    target_ms = max(0, target_ms)
    player.set_time(target_ms)
    time.sleep(0.08)

    return target_ms / 1000.0


def first_event_index_after(
    events: list[MatchEvent],
    time_s: float,
) -> int:
    times = [event.time_s for event in events]
    return bisect.bisect_right(times, time_s)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Prototype A：播放视频并按 events.csv "
            "向 ESP32 发送事件指令。"
        )
    )

    parser.add_argument(
        "video",
        type=Path,
        help="原始比赛视频路径",
    )

    parser.add_argument(
        "events",
        type=Path,
        help="analyze_events.py 生成的 events.csv",
    )

    parser.add_argument(
        "--port",
        required=True,
        help="ESP32 串口，例如 COM3",
    )

    parser.add_argument(
        "--baud",
        type=int,
        default=115200,
    )

    parser.add_argument(
        "--min-confidence",
        type=float,
        default=0.55,
        help="只触发不低于该置信度的事件",
    )

    parser.add_argument(
        "--trigger-offset-s",
        type=float,
        default=0.0,
        help=(
            "统一调整触发时间。负数表示提前，"
            "例如 -0.3 表示提前 0.3 秒"
        ),
    )

    parser.add_argument(
        "--trigger-tolerance-ms",
        type=float,
        default=120.0,
        help="允许的事件触发时间容差",
    )

    parser.add_argument(
        "--start-at",
        type=float,
        default=0.0,
        help="从视频第几秒开始",
    )

    parser.add_argument(
        "--duration",
        type=float,
        default=None,
        help="只测试指定秒数",
    )

    parser.add_argument(
        "--retrigger-on-rewind",
        action="store_true",
        help="后退播放后允许已触发事件再次触发",
    )

    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("prototype_a_sync_output"),
    )

    parser.add_argument(
        "--vlc-dir",
        type=Path,
        default=None,
        help=r"VLC 文件夹，例如 C:\Program Files\VideoLAN\VLC",
    )

    parser.add_argument(
        "--mute-video",
        action="store_true",
        help="视频静音，仅用于调试",
    )

    return parser.parse_args()


def main() -> int:
    args = parse_args()

    video_path = args.video.resolve()
    events_path = args.events.resolve()

    if not video_path.exists():
        print(f"视频不存在：{video_path}", file=sys.stderr)
        return 2

    if not events_path.exists():
        print(f"事件文件不存在：{events_path}", file=sys.stderr)
        return 2

    if not 0.0 <= args.min_confidence <= 1.0:
        print(
            "min-confidence 必须在 0 到 1 之间。",
            file=sys.stderr,
        )
        return 2

    if args.start_at < 0:
        print("start-at 不能为负数。", file=sys.stderr)
        return 2

    if args.trigger_tolerance_ms < 0:
        print(
            "trigger-tolerance-ms 不能为负数。",
            file=sys.stderr,
        )
        return 2

    events = load_events(
        events_path,
        minimum_confidence=args.min_confidence,
        trigger_offset_s=args.trigger_offset_s,
    )

    vlc = import_vlc(args.vlc_dir)

    print(f"已加载事件：{len(events)} 个")
    print(
        "事件统计："
        + "  ".join(
            f"{name}={sum(1 for item in events if item.event == name)}"
            for name in ["SHOT", "FOUL", "PENALTY", "GOAL"]
        )
    )

    serial_port: serial.Serial | None = None
    player = None
    reader_thread: threading.Thread | None = None
    reader_stop = threading.Event()
    serial_queue: queue.Queue[SerialRecord] = queue.Queue()

    (
        sensor_file,
        event_log_file,
        sensor_writer,
        event_writer,
        sensor_path,
        event_log_path,
    ) = create_log_files(args.output_dir.resolve())

    return_code = 0

    try:
        serial_port = serial.Serial(
            port=args.port,
            baudrate=args.baud,
            timeout=0.05,
            write_timeout=1.0,
        )

        if not wait_for_ping(serial_port):
            raise RuntimeError(
                "没有收到 ACK,PONG。请确认 ESP32 中已上传 "
                "Prototype A Arduino 主程序，并关闭串口监视器。"
            )

        reader_thread = threading.Thread(
            target=serial_reader,
            args=(serial_port, serial_queue, reader_stop),
            daemon=True,
        )
        reader_thread.start()

        instance = vlc.Instance("--no-video-title-show")
        media = instance.media_new(str(video_path))
        player = instance.media_player_new()
        player.set_media(media)

        if args.mute_video:
            player.audio_set_mute(True)

        print("开始播放视频...")
        player.play()
        wait_until_playing(player, vlc)

        if args.start_at > 0:
            player.set_time(round(args.start_at * 1000))
            time.sleep(0.15)

        current_video_s = max(0.0, player.get_time() / 1000.0)
        previous_video_s = current_video_s

        next_event_index = first_event_index_after(
            events,
            current_video_s,
        )

        fired_rows: set[int] = set()
        test_start_video_s = current_video_s
        tolerance_s = args.trigger_tolerance_ms / 1000.0
        last_safe_state: str | None = None

        print("同步运行中。")
        print(
            "键盘控制：空格 暂停/继续，A/D ±10秒，"
            "J/L ±30秒，Q 退出。"
        )

        while True:
            state = player.get_state()
            drain_serial_queue(
                serial_queue,
                sensor_writer,
                player,
            )

            if reader_stop.is_set():
                raise RuntimeError("ESP32 串口连接中断。")

            command = get_console_command()

            if command == "quit":
                print("收到退出指令。")
                break

            if command == "toggle_pause":
                if state == vlc.State.Playing:
                    player.pause()
                    send_line(serial_port, "STOP")
                    print("视频已暂停，反馈已停止。")
                else:
                    player.play()
                    print("视频继续播放。")
                time.sleep(0.15)
                continue

            if command in {
                "rewind_10",
                "forward_10",
                "rewind_30",
                "forward_30",
            }:
                offsets = {
                    "rewind_10": -10.0,
                    "forward_10": 10.0,
                    "rewind_30": -30.0,
                    "forward_30": 30.0,
                }

                old_time_s = max(
                    0.0,
                    player.get_time() / 1000.0,
                )
                new_time_s = seek_player(
                    player,
                    offsets[command],
                )

                send_line(serial_port, "STOP")

                if (
                    new_time_s < old_time_s
                    and args.retrigger_on_rewind
                ):
                    fired_rows = {
                        row
                        for row in fired_rows
                        if next(
                            (
                                event.time_s
                                for event in events
                                if event.source_row == row
                            ),
                            -1.0,
                        )
                        < new_time_s
                    }

                next_event_index = first_event_index_after(
                    events,
                    new_time_s,
                )
                previous_video_s = new_time_s

                print(f"已跳转至 {new_time_s:.2f} 秒。")
                continue

            if state == vlc.State.Playing:
                video_ms = player.get_time()

                if video_ms < 0:
                    time.sleep(0.005)
                    continue

                current_video_s = video_ms / 1000.0

                if (
                    args.duration is not None
                    and current_video_s - test_start_video_s
                    >= args.duration
                ):
                    print("已达到指定测试时长。")
                    break

                # Detect external or VLC-internal seeking.
                time_jump = current_video_s - previous_video_s

                if time_jump < -1.0:
                    if args.retrigger_on_rewind:
                        fired_rows = {
                            row
                            for row in fired_rows
                            if next(
                                (
                                    event.time_s
                                    for event in events
                                    if event.source_row == row
                                ),
                                -1.0,
                            )
                            < current_video_s
                        }

                    next_event_index = first_event_index_after(
                        events,
                        current_video_s,
                    )
                    previous_video_s = current_video_s

                elif time_jump > 2.0:
                    # A large forward seek should not trigger all skipped events.
                    next_event_index = first_event_index_after(
                        events,
                        current_video_s,
                    )
                    previous_video_s = current_video_s

                while next_event_index < len(events):
                    event = events[next_event_index]

                    if event.time_s > current_video_s + tolerance_s:
                        break

                    crossed_event = (
                        event.time_s > previous_video_s - tolerance_s
                    )

                    if (
                        crossed_event
                        and event.source_row not in fired_rows
                    ):
                        serial_command = f"EVENT,{event.event}"
                        send_line(serial_port, serial_command)
                        fired_rows.add(event.source_row)

                        host_time = dt.datetime.now().isoformat(
                            timespec="milliseconds"
                        )

                        event_writer.writerow(
                            [
                                host_time,
                                f"{current_video_s:.3f}",
                                f"{event.time_s:.3f}",
                                event.event,
                                f"{event.confidence:.3f}",
                                serial_command,
                                event.text,
                            ]
                        )

                        print(
                            f"[{current_video_s:8.2f}s] "
                            f"{serial_command}  "
                            f"confidence={event.confidence:.2f}"
                        )

                    next_event_index += 1

                previous_video_s = current_video_s
                last_safe_state = None

            elif state == vlc.State.Paused:
                if last_safe_state != "paused":
                    send_line(serial_port, "STOP")
                    print("视频暂停，反馈输出已停止。")
                    last_safe_state = "paused"

            elif state in (
                vlc.State.Ended,
                vlc.State.Stopped,
            ):
                print("视频播放结束。")
                break

            elif state == vlc.State.Error:
                raise RuntimeError("VLC 播放发生错误。")

            else:
                if last_safe_state != "not_playing":
                    send_line(serial_port, "STOP")
                    last_safe_state = "not_playing"

            time.sleep(0.005)

    except KeyboardInterrupt:
        print("\n收到 Ctrl+C。")

    except Exception as error:
        print(f"\n运行失败：{error}", file=sys.stderr)
        return_code = 1

    finally:
        if serial_port is not None and serial_port.is_open:
            try:
                send_line(serial_port, "STOP")
                time.sleep(0.05)
            except Exception:
                pass

        if player is not None:
            try:
                player.stop()
            except Exception:
                pass

        reader_stop.set()

        if reader_thread is not None:
            reader_thread.join(timeout=1.0)

        if player is not None:
            drain_serial_queue(
                serial_queue,
                sensor_writer,
                player,
            )

        sensor_file.close()
        event_log_file.close()

        if serial_port is not None and serial_port.is_open:
            serial_port.close()

        print(f"传感器日志：{sensor_path}")
        print(f"事件指令日志：{event_log_path}")
        print("已发送 STOP，反馈输出关闭。")

    return return_code


if __name__ == "__main__":
    raise SystemExit(main())