export class RelayProtocolError extends Error {
  constructor(code, message, details = undefined) {
    super(message);
    this.name = "RelayProtocolError";
    this.code = code;
    this.details = details;
  }
}

function requireObject(value, label = "message") {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    throw new RelayProtocolError(
      "INVALID_MESSAGE",
      `${label} must be a JSON object.`
    );
  }
}

function requireString(value, field, { min = 1, max = 128, pattern } = {}) {
  if (typeof value !== "string") {
    throw new RelayProtocolError("INVALID_FIELD", `${field} must be a string.`);
  }

  const normalized = value.trim();
  if (normalized.length < min || normalized.length > max) {
    throw new RelayProtocolError(
      "INVALID_FIELD",
      `${field} must contain ${min} to ${max} characters.`
    );
  }

  if (pattern && !pattern.test(normalized)) {
    throw new RelayProtocolError(
      "INVALID_FIELD",
      `${field} contains unsupported characters.`
    );
  }

  return normalized;
}

function requireInteger(value, field, minimum, maximum) {
  if (!Number.isSafeInteger(value) || value < minimum || value > maximum) {
    throw new RelayProtocolError(
      "INVALID_FIELD",
      `${field} must be an integer between ${minimum} and ${maximum}.`
    );
  }
  return value;
}

function requireNumber(value, field, minimum, maximum) {
  if (
    typeof value !== "number" ||
    !Number.isFinite(value) ||
    value < minimum ||
    value > maximum
  ) {
    throw new RelayProtocolError(
      "INVALID_FIELD",
      `${field} must be a finite number between ${minimum} and ${maximum}.`
    );
  }
  return value;
}

function requireProtocolVersion(value, expectedVersion) {
  return requireInteger(value, "protocolVersion", expectedVersion, expectedVersion);
}

const MATCH_ID_PATTERN = /^[A-Za-z0-9._:-]+$/;

/**
 * Validates the JSON generated by CloudEmotionMessage in the stadium iOS code.
 * The returned object preserves eventUtcMs, sequence, CES and Spike exactly.
 */
export function validateEmotionMessage(value, expectedVersion = 1) {
  requireObject(value);

  if (value.type !== "emotion") {
    throw new RelayProtocolError(
      "INVALID_TYPE",
      "Emotion messages must use type='emotion'."
    );
  }

  const message = {
    type: "emotion",
    protocolVersion: requireProtocolVersion(
      value.protocolVersion,
      expectedVersion
    ),
    matchID: requireString(value.matchID, "matchID", {
      min: 1,
      max: 96,
      pattern: MATCH_ID_PATTERN
    }),
    source: requireString(value.source, "source", { min: 1, max: 64 }),

    deviceID: requireInteger(value.deviceID, "deviceID", 0, 255),
    sequence: requireInteger(value.sequence, "sequence", 0, 0xFFFFFFFF),
    eventUtcMs: requireInteger(
      value.eventUtcMs,
      "eventUtcMs",
      0,
      Number.MAX_SAFE_INTEGER
    ),
    receivedUtcMs: requireInteger(
      value.receivedUtcMs,
      "receivedUtcMs",
      0,
      Number.MAX_SAFE_INTEGER
    ),
    deviceTimestampMs: requireInteger(
      value.deviceTimestampMs,
      "deviceTimestampMs",
      0,
      Number.MAX_SAFE_INTEGER
    ),

    ces: requireNumber(value.ces, "ces", 0, 1),
    spike: requireNumber(value.spike, "spike", 0, 1),
    audio: requireNumber(value.audio, "audio", 0, 1),
    heart: requireNumber(value.heart, "heart", 0, 1),
    motion: requireNumber(value.motion, "motion", 0, 1),
    bpm: requireInteger(value.bpm, "bpm", 0, 255),
    fusionQuality: requireNumber(
      value.fusionQuality,
      "fusionQuality",
      0,
      1
    ),
    statusFlags: requireInteger(value.statusFlags, "statusFlags", 0, 255)
  };

  return Object.freeze(message);
}

/**
 * Home App subscription message:
 * {
 *   type: "subscribe",
 *   protocolVersion: 1,
 *   role: "home",
 *   matchID: "demo-match",
 *   resumeAfterEventUtcMs: 1785691220000 // optional
 * }
 */
export function validateSubscribeMessage(value, expectedVersion = 1) {
  requireObject(value);

  if (value.type !== "subscribe" || value.role !== "home") {
    throw new RelayProtocolError(
      "INVALID_SUBSCRIPTION",
      "A Home App must send type='subscribe' and role='home'."
    );
  }

  const resumeAfterEventUtcMs =
    value.resumeAfterEventUtcMs === undefined
      ? null
      : requireInteger(
          value.resumeAfterEventUtcMs,
          "resumeAfterEventUtcMs",
          0,
          Number.MAX_SAFE_INTEGER
        );

  return Object.freeze({
    type: "subscribe",
    protocolVersion: requireProtocolVersion(
      value.protocolVersion,
      expectedVersion
    ),
    role: "home",
    matchID: requireString(value.matchID, "matchID", {
      min: 1,
      max: 96,
      pattern: MATCH_ID_PATTERN
    }),
    resumeAfterEventUtcMs
  });
}

export function validateUnsubscribeMessage(value, expectedVersion = 1) {
  requireObject(value);

  if (value.type !== "unsubscribe") {
    throw new RelayProtocolError(
      "INVALID_TYPE",
      "Unsubscribe messages must use type='unsubscribe'."
    );
  }

  return Object.freeze({
    type: "unsubscribe",
    protocolVersion: requireProtocolVersion(
      value.protocolVersion,
      expectedVersion
    )
  });
}

export function parseJsonMessage(rawData, isBinary) {
  if (isBinary) {
    throw new RelayProtocolError(
      "BINARY_NOT_SUPPORTED",
      "Cloud Relay messages must be UTF-8 JSON text."
    );
  }

  let value;
  try {
    value = JSON.parse(rawData.toString("utf8"));
  } catch {
    throw new RelayProtocolError("INVALID_JSON", "Message is not valid JSON.");
  }

  requireObject(value);
  return value;
}
